branches:
  only:
  - master
  - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
language: python
matrix:
  include:
  - python: 3.6
  - python: 3.5
  - python: 2.7
  - os: osx
    language: generic
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew install python3
    - virtualenv env -p python3
    - source env/bin/activate
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    install:
    - docker pull $DOCKER_IMAGE
    script:
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
    - if [[ $TRAVIS_TAG ]]; then pip install twine && twine upload -u datamade.wheelbuilder
      -p $PYPIPASSWORD --skip-existing wheelhouse/*; fi
    - exit 0
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    install:
    - docker pull $DOCKER_IMAGE
    script:
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
    - if [[ $TRAVIS_TAG ]]; then pip install twine && twine upload -u datamade.wheelbuilder
      -p $PYPIPASSWORD --skip-existing wheelhouse/*; fi
    - exit 0
install:
- pip install --upgrade pip
- pip install numpy
- pip freeze
- pip install --upgrade -r requirements.txt
- cython lbfgs/_lowlevel.pyx
- pip install -e .
script:
- pytest tests --cov lbfgs
after_success:
- pip install coveralls
- coveralls
deploy:
- provider: pypi
  skip_cleanup: true
  user: datamade.wheelbuilder
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
  distributions: bdist_wheel
  password: "$PYPIPASSWORD"
- provider: pypi
  skip_cleanup: true
  user: datamade.wheelbuilder
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
  distributions: sdist
  password: "$PYPIPASSWORD"
env:
  global:
  - secure: h2cFDu/I4tXx5ObUypZ7CDA+q9tRlklqIeZh+ysfg2FT7aat9mH3MPOACnBF/KNHMI+pBztGdUSjLkwFESjr7OqyXA6Y/tQiPy77O4h38c0px6kaZcvCOZy6c0qhYZQuTNggMhj1+WfaSucqntlhcqGGOhrIkJcBSgUsl7zC/FE=
